# Generated by Django 2.1.5 on 2019-01-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
    ]
