# Generated by Django 2.1.5 on 2019-01-29 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual_app', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ifm_loan_appl',
        ),
        migrations.DeleteModel(
            name='qsh_loan_appl',
        ),
        migrations.DeleteModel(
            name='sxh_loan_appl',
        ),
        migrations.DeleteModel(
            name='tty_loan_appl',
        ),
    ]
